version: "3.4"

services:
  intch.mongodb:
    image: mongo:3.6
    container_name: intch_mognodb
    ports:
      - "27017:27017"
    volumes:
      - C:/Mongo/data/db:/data/db/

  intch.redis:
    image: redis:latest
    container_name: intch_redis
    ports:
      - "6379:6379"

  intch.nats:
    image: nats-streaming
    container_name: intch_nats
    hostname: nats-srv
    expose:
      - "4222"

  intch.nginx:
    image: nginx
    container_name: intch_nginx
    ports:
      - 2020:80
    depends_on:
      - intch.auth
      - intch.client
      - intch.chat
    build:
      dockerfile: Dockerfile-dev
      context: ./web-app/nginx

  intch.auth:
    image: intch/auth:dev
    container_name: intch_auth
    depends_on:
      - intch.mongodb
      - intch.redis
    env_file: 
      - ./auth/.env.dev
    build:
      dockerfile: Dockerfile-dev
      context: ./auth
    volumes:
      - ./auth:/app
      - /app/node_modules

  intch.chat:
    image: intch/chat:dev
    container_name: intch_chat
    depends_on:
      - intch.mongodb
      - intch.redis
    env_file: 
      - ./chat/.env.dev
    build:
      dockerfile: Dockerfile-dev
      context: ./chat
    volumes:
      - ./chat:/app
      - /app/node_modules

  intch.client:
    image: intch/web.client:dev
    container_name: intch_web_client
    depends_on: 
      - intch.auth
      - intch.chat
    build:
      dockerfile: Dockerfile-dev
      context: ./web-app
    volumes:
      - ./web-app:/app
      - /app/node_modules

networks:
  default:
    external:
      name: intch