version: "3.4"

services:
  intch.mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes: 
      - C:/Mongo/data/db:/data/db/

networks:
  default:
    external:
      name: intch
