FROM node:10-alpine

ENV NODE_ENV development

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install
COPY . /app

EXPOSE 4200

CMD ./node_modules/.bin/ng serve --host 0.0.0.0 --port 4200 --disableHostCheck --poll 5000